#!/usr/bin/env bash
# Installs NginX web server

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create a file to store the string 'Hello World'
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo nginx -t

# Start Nginx
sudo service nginx start
