#!/usr/bin/env bash
# Installs NginX web server

# Update package list
sudo apt update

# Create a file to store the string 'Hello World'
echo "
<html>
   <head>
     <title>Hello World!</title>
  </head>
     <body>
        <h1>Hello World!</h1>
     </body>
</html>
" | sudo tee /www/index.html


# Install Nginx
sudo apt install -y nginx

# Start Nginx
sudo service nginx start
