#!/usr/bin/ env bash

#I want to configure web-02 to be identical as web-01
# install nginx server and configure it to port 80

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html

echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        add_header X-Served-By $HOSTNAME;
        root /var/www/html;
        index index.html;
        location /redirect_me {
                return 301 https://github.com;
        }

        error_page 404 /404.html;
        location = /404.html{
        internal;
        }
}" > default

sudo mv -f default /etc/nginx/sites-enabled/default
sudo service nginx restart
