#!/usr/bin/env bash
# Create a script to install and configure HAProxy

sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend fae_frontend
        bind *:80
        mode http
        default_backend eric_backend
backend fae_backend
        balance roundrobin
        server 357156-web-01 52.91.118.183:80 check
        server 357156-web-02 52.3.247.249:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
